Bug 32030: Fix datatable.js order_by
Getting Uncaught (in promise) TypeError: order_by.split is not a function
Because data is an array: "data": ["me.package_id", "me.name"],

If we modify it with "data": "me.package_id:me.name",
(what we are using in other places) we are getting the following warning
when the table is init:
"Requested unknown parameter 'me.package_id:me.name' for row 0, column 0. For more information about this error"

Signed-off-by: Jonathan Field <jonathan.field@ptfs-europe.com>

Signed-off-by: Martin Renvoize <martin.renvoize@ptfs-europe.com>
Signed-off-by: Kyle M Hall <kyle@bywatersolutions.com>
Signed-off-by: Tomas Cohen Arazi <tomascohen@theke.io>