Bug 38255: Fix Cash registers
This patch fixes the following error:
 Uncaught TypeError: table.column is not a function

We needed to pass table.DataTable() to filterDataTable
I've decided to clean the code as it does not make sense to me:
filterDataTable is called from a single place, and clearFilter is not
needed (we should not interfer with the 'Clear filter' button here)

Signed-off-by: Lucas Gass <lucas@bywatersolutions.com>
Signed-off-by: Martin Renvoize <martin.renvoize@ptfs-europe.com>
Signed-off-by: Katrin Fischer <katrin.fischer@bsz-bw.de>