Bug 21553: Remove JS error on the Rota view
JS error was:
 ReferenceError: _ is not defined

The strings after staff-global.js (for the function _)

Test plan:
Turn on StockRotation system preference

1) Go to a staff detail page
2) Switch to rota page
3) Check web developer tools

Signed-off-by: Owen Leonard <oleonard@myacpl.org>
Signed-off-by: Martin Renvoize <martin.renvoize@ptfs-europe.com>
Signed-off-by: Tomas Cohen Arazi <tomascohen@theke.io>