Bug 38465: (bug 36454 follow-up) Fix curbside pickup's patron autocomplete
js-date-format.inc already include those 2 JS files. If had them in
curbside pickups template because it was the first using dayjs.
Now it's included in js_includes.inc.

Test plan:
Configure curbside pickup for your library and go to circ/curbside_pickups.pl
Last tab, search for a patron
Without this patch you get a JS error:
 Uncaught TypeError: m.tz is not a function
With this patch applied the patron autocomplete is fixed

Signed-off-by: David Nind <david@davidnind.com>

Signed-off-by: Marcel de Rooy <m.de.rooy@rijksmuseum.nl>
Signed-off-by: Katrin Fischer <katrin.fischer@bsz-bw.de>
(cherry picked from commit decb8780acd949249aaa348c3fd378c251de6208)
Signed-off-by: Paul Derscheid <paul.derscheid@lmscloud.de>