Bug 40774: Fix EBSCO's package list view
TypeError: can't access property "authorised_values", e.type is undefined
Signed-off-by: Christian Nelson <christian.nelson@uwasa.fi>
Signed-off-by: Paul Derscheid <paul.derscheid@lmscloud.de>
Signed-off-by: Lucas Gass <lucas@bywatersolutions.com>
(cherry picked from commit af8efd85ec4ae944b7730d434a01e6cf21182358)
Signed-off-by: Paul Derscheid <paul.derscheid@lmscloud.de>