Bug 9613: items namespace missing in XSLT
In some XSLT, "items" namespace is used in exclude-result-prefixes but is not defined.

This patch add this namespace where missing.
Also corrects a koha.org, instead of koha-community.org, in one namespace URL.

Test plan :
- Enable XSLT on search results
- Perform a search
=> Look at error logs to check that there is no xsl error like :
[Fri Feb 08 15:35:06 2013] [error] [client 127.0.0.1] [Fri Feb  8 15:35:06 2013] opac-search.pl: compilation error: file koha-tmpl/opac-tmpl/prog/en/xslt/UNIMARCslimUtils.xsl line 8 element stylesheet, referer: http://opac.master.community.localhost/cgi-bin/koha/opac-detail.pl?biblionumber=299
[Fri Feb 08 15:35:06 2013] [error] [client 127.0.0.1] [Fri Feb  8 15:35:06 2013] opac-search.pl: xsl:exclude-result-prefixes : undefined namespace items, referer: http://opac.master.community.localhost/cgi-bin/koha/opac-detail.pl?biblionumber=299

Signed-off-by: Kyle M Hall <kyle@bywatersolutions.com>
Signed-off-by: Mathieu Saby <mathieu.saby@univ-rennes2.fr>
Passed-QA-by: Marcel de Rooy <m.de.rooy@rijksmuseum.nl>
With comment on Bugzilla.

Signed-off-by: Paul Poulain <paul.poulain@biblibre.com>
Signed-off-by: Jared Camins-Esakov <jcamins@cpbibliography.com>