Bug 33066: Fix dt - no need to reselect
Bug 33066: (follow-up) Fix dt - no need to reselect

Patron search result table was not displayed correctly
Uncaught TypeError: this.on is not a function

Signed-off-by: Pedro Amorim <pedro.amorim@ptfs-europe.com>

Signed-off-by: Agustín Moyano <agustinmoyano@theke.io>
Signed-off-by: Tomas Cohen Arazi <tomascohen@theke.io>
(cherry picked from commit 75eaa1f5c58d224b48c332fd8eac31108eb9f375)
Signed-off-by: Martin Renvoize <martin.renvoize@ptfs-europe.com>