Bug 40943: Fix Serials.t
We need to mock userenv
ERROR: Plugin dateaccessioned.pl: Can't use an undefined value as a HASH reference at /kohadevbox/koha/cataloguing/value_builder/dateaccessioned.pl line 30.

Signed-off-by: Lucas Gass <lucas@bywatersolutions.com>