Bug 41065: (bug 26553 follow-up) Remove JS error when submitting the form
Uncaught TypeError: patron_table.$ is not a function

Signed-off-by: Nick Clemens <nick@bywatersolutions.com>
Signed-off-by: Lucas Gass <lucas@bywatersolutions.com>
(cherry picked from commit ea123185b90da00faa7ddd3f26e8d5b3ae1db256)
Signed-off-by: Paul Derscheid <paul.derscheid@lmscloud.de>