Bug 35940: (bug 35477 follow-up) Fix cypress tests
AssertionError: Timed out retrying after 10000ms: Expected to find element: `main div[class='dialog message']`, but never found it.

We moved from message to alert.

Signed-off-by: Katrin Fischer <katrin.fischer@bsz-bw.de>
(cherry picked from commit f1b32b5316f6b204d6451a1902a0e510fa498f90)
Signed-off-by: Fridolin Somers <fridolin.somers@biblibre.com>